export default {
  ADD_TRACK: 'ADD_TRACK',
  TOGGLE_SEGMENT_DISPLAY: 'TOGGLE_SEGMENT_DISPLAY',
  TOGGLE_SEGMENT_EDITING: 'TOGGLE_SEGMENT_EDITING',
  CHANGE_SEGMENT_POINT: 'CHANGE_SEGMENT_POINT',
  REMOVE_SEGMENT_POINT: 'REMOVE_SEGMENT_POINT',
  EXTEND_SEGMENT_POINT: 'EXTEND_SEGMENT_POINT',
  ADD_SEGMENT_POINT: 'ADD_SEGMENT_POINT',
  REMOVE_SEGMENT: 'REMOVE_SEGMENT',
  SPLIT_SEGMENT: 'SPLIT_SEGMENT',
  TOGGLE_SEGMENT_SPLITING: 'TOGGLE_SEGMENT_SPLITING',
  TOGGLE_SEGMENT_JOINING: 'TOGGLE_SEGMENT_JOINING',
}
